services:
  postgres:
    image: postgres:bullseye
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - a9shw:/data/postgres-hw
    ports:
      - "5432:5432"
    restart: unless-stopped
    stdin_open: true
    tty: true
volumes:
    a9shw:
      external: true
